### ISSUE TITLE
Can't change root password

### ISSUE THREAD

**Issue by mcpacific** [OnApp/SolusVM-WHMCS-Module#1]
It doesn't seem that this module works, as far as changing root password from Admin area. The button's don't function. Also, changing the root password from the Client Area doesn't update WHMCS. Also, where is "rootpassword.php", as indicated in line 58 of custom-example.php?

**Comment by prado1991** [comment]
Default template has changing root password functionality, for custom.php it will be implemented in next release.

**Comment by mcpacific** [comment]
I'm also confused about the Configurable Option for Control Panel. If the customer chooses to purchase the Annual License, WHMCS will bill them each month for the annual amount, will it not?

**Comment by prado1991** [comment]
There is a possibility to configure WHMCS for a different Payment Types:
http://docs.whmcs.com/Products_and_Services
http://docs.whmcs.com/File:Price_grid.png
