### ISSUE TITLE
KVM whmcs HDD Activity Graph for client and admin

### ISSUE THREAD

**Issue by orbwalk** [OnApp/SolusVM-WHMCS-Module#10]
It looks like TRAFFIC and HDD Activity Graphs are available in SolusVM for KVM virt.  Could you add the HDD Activity  graph in the next update so they can be seen in client area and whmcs admin area?

**Comment by sixteeN11** [comment]
Not possible for KVM

**Comment by prado1991** [comment]
will be added in new version
