### ISSUE TITLE
Upgrade dont work

### ISSUE THREAD

**Issue by sixteeN11** [OnApp/SolusVM-WHMCS-Module#11]
The Module does not support upgrade any individual Server (CPU, RAM, HDD) setting at this Time.
The Customer orders a RAM Upgrade from 1G to 2G and the Module write the "default Plan" in the VM Ressources.

**Comment by jas8522** [comment]
This *should* be fixed with version 4.0.7: https://github.com/OnApp/SolusVM-WHMCS-Module/commit/a130b4c300bbc6284d9d46b99dd934bf7727d711
