### ISSUE TITLE
Curl class needs new namespace?

### ISSUE THREAD

**Issue by jas8522** [OnApp/SolusVM-WHMCS-Module#13]
Trying to load the same class via composer in a different WHMCS module, but I get:
`Fatal error: Cannot declare class Curl\Curl, because the name is already in use in [path_to_vhost]/whmcs/modules/servers/solusvmpro/lib/Curl.php on line 6`

Is it possible to have the namespace adjusted to the Curl class and its helper class to something like SolusVM\Curl\Curl ?

I've tried changing my own so it's [module]\Curl\Curl but it still seems to conflict with yours :(

**Comment by prado1991** [comment]
fixed in ver. 4.0.8-3
