### ISSUE TITLE
WHMCS ERROR !

### ISSUE THREAD

**Issue by matheussalles** [OnApp/SolusVM-WHMCS-Module#18]
Hello why my whmcs give this error? http://prntscr.com/hdzi5m

**Comment by matheussalles** [comment]
From what I saw and a whmcs connection with the master that is not picking up! But I already checked everything and I do not know what it can be!

**Comment by matheussalles** [comment]
Print's: http://prntscr.com/he04if - http://prntscr.com/he04ny

**Comment by prado1991** [comment]
Seems you have issue with ssl verification(unencypted connection), try to add in whmcs admin area->setup->product/services->servers->edit server->Server Details->Access Hash (Instead of password for cPanel servers) next params:
<ssl_verifypeer>no</ssl_verifypeer>
<ssl_verifyhost>no</ssl_verifyhost>

**Comment by matheussalles** [comment]
Hello, how can I use the callback because of the error always I have to make a config plus dessa http://prntscr.com/hj3bdk! Because of this error always> http://prntscr.com/hj3crf http://prntscr.com/hj3dcz
