### ISSUE TITLE
VNC doesn't work from admin area

### ISSUE THREAD

**Issue by cyber4len** [OnApp/SolusVM-WHMCS-Module#19]
https://github.com/OnApp/SolusVM-WHMCS-Module/blob/4a90437b9a788dc52c52efbbb83bd2321249977e/modules/servers/solusvmpro/vnc.php#L28

This check only verifies that the user is logged in to client area. However, admin area uses the same file and if any admin tries to open VNC (from the product details in admin area), it immediately throws "Unauthorized" error.

**Comment by prado1991** [comment]
fixed in 4.0.9-3
