### ISSUE TITLE
fix html5console.php for proper parent directory - changes are lost

### ISSUE THREAD

**Issue by cyber4len** [OnApp/SolusVM-WHMCS-Module#20]
https://github.com/OnApp/SolusVM-WHMCS-Module/blob/87ab18ea5f399fe11ca81d2b9b88947f750c382f/modules/servers/solusvmpro/html5console.php#L18-L47

changes implemented in 95abc80ed656b4657cc9012ef0db159b117b610b were lost due to a130b4c300bbc6284d9d46b99dd934bf7727d711

**Comment by prado1991** [comment]
it's a right paths to assets files, no sense to rewrite it like in 95abc80.
try :
{your_whmcs_url}/assets/css/bootstrap.min.css
{your_whmcs_url}/assets/css/font-awesome.min.css
{your_whmcs_url}/assets/js/jquery.min.js
etc..

**Comment by cyber4len** [comment]
In case WHMCS is installed in subdirectory (e.g. https://example.com/whmcs/) absolute path to "assets" won't work, that is why it's suggested to use relative path.

**Comment by ju5t** [comment]
This looks like an issue with your WHMCS template. If you have `<base href="URI">` in your WHMCS template this should work.

**Comment by prado1991** [comment]
fixed in 4.0.9-4
