### ISSUE TITLE
callback not working

### ISSUE THREAD

**Issue by PhiGi87** [OnApp/SolusVM-WHMCS-Module#21]
Hi, callback is not working. I Become no Errors or Responses, only the Log from Solus:

> url => https://myurl.de/modules/servers/solusvmpro/callback.php
> content_type => text/html; charset=UTF-8
> http_code => 200
> header_size => 178
> request_size => 201
> filetime => -1
> ssl_verify_result => 0
> redirect_count => 0
> total_time => 0.238878
> namelookup_time => 0.000678
> connect_time => 0.001164
> pretransfer_time => 0.0751
> size_upload => 571
> size_download => 0
> speed_download => 0
> speed_upload => 2390
> download_content_length => -1
> upload_content_length => 571
> starttransfer_time => 0.07517
> redirect_time => 0
> certinfo => Array
> 
> * About to connect() to myurl.de port 443 (#0)
> *   Trying 213.202.252.150... * connected
> * Connected to myurl.de (213.202.252.150) port 443 (#0)
> * Initializing NSS with certpath: sql:/etc/pki/nssdb
> * skipping SSL peer certificate verification
> * SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> * Server certificate:
> * 	subject: CN=myurl.de
> * 	start date: Oct 04 19:22:34 2017 GMT
> * 	expire date: Jan 02 19:22:34 2018 GMT
> * 	common name: myurl.de
> * 	issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> > POST /modules/servers/solusvmpro/callback.php HTTP/1.1
> Host: myurl.de
> Accept: */*
> Content-Length: 571
> Content-Type: multipart/form-data; boundary=----------------------------d61f60a44213
> 
> < HTTP/1.1 200 OK
> < Date: Tue, 28 Nov 2017 12:12:05 GMT
> < Server: Apache
> < Upgrade: h2,h2c
> < Connection: Upgrade
> < Transfer-Encoding: chunked
> < Content-Type: text/html; charset=UTF-8
> < 
> * Connection #0 to host myurl.de left intact
> * Closing connection #0

Thanks for Help

**Comment by prado1991** [comment]
Can't reproduce this issue in dev environment, seems you did mistake in configuring SolusVM WHMCS module or SolusVM Admin Area. Please follow the instructions:
https://documentation.solusvm.com/display/DOCS/Callbacks
or give credentials for deeper investigation

**Comment by matheussalles** [comment]
Hello, how can I use the callback because of the error always I have to make a config plus dessa http://prntscr.com/hj3bdk! Because of this error always> http://prntscr.com/hj3crf http://prntscr.com/hj3dcz

**Comment by sixteeN11** [comment]
Hi, i cant use the callback in the newest WHMCS.
We receive the same error always

**Comment by prado1991** [comment]
@matheussalles 
https://prnt.sc/hj3bdk - you set URL to callback file with https, but on others pics it's http.
Check configurations and callback file one more time, because it works on dev env.

**Comment by matheussalles** [comment]
Same mistake !!!!!!! http://prntscr.com/hn13as

**Comment by sixteeN11** [comment]
HTTP or HTTPS - Same Issue as bevor.

**Comment by sixteeN11** [comment]
Please do something?!

**Comment by prado1991** [comment]
@sixteeN11 Can't reproduce this issue on dev env, need more details to reproduce this issue. Can you check Solusvm admin->Logs->Callback Log 

this is my Callback Log: 
![solusvm callback](https://user-images.githubusercontent.com/7640639/34434198-18219e7e-ec8d-11e7-9d45-12df38be3bd2.png)

**Comment by matheussalles** [comment]
http://prntscr.com/htrqc8

**Comment by prado1991** [comment]
@matheussalles Seems smth wrong with configuration...
try to do a simple test script on solusVM master server for testing connection to WHMCS: 

vi /tmp/test.php
<?php
    $postfields["hash"] = $hash; // from General Settings->callback->hash
    $postfields["action"] = $action; // callback action - suspend, unsuspend etc
    $postfields["vserverid"] = $vserverid; // server id

    $ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'https:://whmcs_url/modules/servers/solusvmpro/callback.php');// change it!
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 60);
    curl_setopt($ch, CURLOPT_FRESH_CONNECT, 1);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_HTTPHEADER, ["Expect:"]);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($ch, CURLOPT_VERBOSE, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $postfields);
    $data = curl_exec($ch);
	$data = curl_exec($ch);
	var_dump($data);

and run it:
/usr/local/svmstack/php/bin/php /tmp/test.php

**Comment by matheussalles** [comment]
After creating this file and putting the link from my whmcs how do I perform it?

**Comment by prado1991** [comment]
after adding all params run the script:
> /usr/local/svmstack/php/bin/php /tmp/test.php

**Comment by matheussalles** [comment]
![screenshot_1](https://user-images.githubusercontent.com/31084533/34437531-3d47dd96-ec86-11e7-898b-525676447a4b.png)


Hello I run and it returns nothing to me!

**Comment by prado1991** [comment]
@matheussalles try to debug it deeper and find why it returns nothing.
without server access, can't say for sure what the problem is
(you can contact me - ivan.gavrilyuk@onapp.com)

**Comment by matheussalles** [comment]
![screenshot_1](https://user-images.githubusercontent.com/31084533/34437850-0a83eea6-ec89-11e7-9ffd-63c1c0a26a62.png)

**Comment by prado1991** [comment]
try ivan.gavryliuk@onapp.com

**Comment by prado1991** [comment]
The problem was in configuring callback.php - removing exit() function on line 4

**Comment by noitcennok** [comment]
This issue still not resolved.
