### ISSUE TITLE
WHMCS Not Connecting

### ISSUE THREAD

**Issue by jerome997** [OnApp/SolusVM-WHMCS-Module#25]
is there something wrong? or it isn't compatible with whmcs 7.4.2?

http://prntscr.com/ivrev9 - WHMCS
http://prntscr.com/ivrgcz - SolusVM Master

**Comment by jerome997** [comment]
I tried debugging it and this is what came out after saving the changes without choosing anything http://prntscr.com/ivs232

**Comment by prado1991** [comment]
try to add into Server Details->Access Hash next Hashes:
<ssl_verifypeer>no</ssl_verifypeer>
<ssl_verifyhost>no</ssl_verifyhost>
<clientkeyauth>Enable</clientkeyauth>
