### ISSUE TITLE
HTML5 Console does not work in WHMCS

### ISSUE THREAD

**Issue by jas8522** [OnApp/SolusVM-WHMCS-Module#4]
I've enabled the HTML5 console in SolusVM and it works great from the Solus admin area.

When trying to access it as a client in WHMCS, the window pops up and I can create the session, but it just says:

Connecting...Connection closed

Web inspector says:

WebSocket connection to 'wss://[NODE_IP]:5021/ssh/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Shouldn't it be connecting to the Master IP, not the Node IP?

-Jordan

**Comment by jas8522** [comment]
I attempted to set the master server hostname by hard coding it (for testing only), which avoids the above error, but for some reason it seems unable to actually provide me with an active session. Rather than resulting in:

> Connecting...Connection closed

Now it just says:

> Connection closed

And there's no errors in the web inspector console. There's also nothing showing in the nginx debug log on the master server: /usr/local/svmstack/sshwebsocket/log/debug.log yet when I connect directly from the SolusVM admin, log entries are added :/

**Comment by prado1991** [comment]
Try to update SolusVM, it should help.
What version of SolusVM you have?

**Comment by jas8522** [comment]
Updated the module to 4.0.5 (reverting my attempts to hard code the master server hostname) and updated SolusVM to 1.19.09. I then attempted to use HTML5 console again from Client Area and I still get:
> Connecting...Connection closed

When I go to the HTML5 Console in SolusVM admin, it loads perfectly.

Note that this is while using OpenVZ containers -- in case that has anything to do with it.

**Comment by prado1991** [comment]
html5 concole bug fixed in module version 4.0.6

**Comment by jas8522** [comment]
Wonderful! Updated and the HTML5console is working great from WHMCS :)

Thanks!
