### ISSUE TITLE
Memory Graph does not reflect correctly on admin or client area

### ISSUE THREAD

**Issue by Anasxrt** [OnApp/SolusVM-WHMCS-Module#7]
Hi,

I have VPS running on OpenVZ. I found that the Memory Graph does not reflect correctly on admin or client area. 

Example - as screen shot attached (Memory Graph show 8 GB but the HTOP show only 4GB memory usage)
![image 1482421786](https://cloud.githubusercontent.com/assets/3105475/21431225/09271390-c899-11e6-8d96-67234e5d6a2e.png)
![image 1482421765](https://cloud.githubusercontent.com/assets/3105475/21431226/09288824-c899-11e6-9b66-53303f45a851.png)

**Comment by prado1991** [comment]
Legend for htop Memory bar:
Green = Used memory
Blue = Buffers
Yellow/Orange = Cache

According to your screenshot there are no free memory left.

**Comment by Anasxrt** [comment]
Hi prado1991, 

Yes, I am mistake here, so the GUI is reflected correctly.
