### ISSUE TITLE
Action Buttons Dont Work

### ISSUE THREAD

**Issue by DavidBrockway** [OnApp/SolusVM-WHMCS-Module#8]
{"success":false,"msg":"solusvmpro_Custom_reboot not found"}

  Overview
Information
  Actions
Reboot
Shutdown
Boot
Request Cancellation

Don't work

**Comment by prado1991** [comment]
We can not reproduce this issue with dafault template.
Could you please provide additional information?

**Comment by DavidBrockway** [comment]
When you click the reboot button in the overview information is goes to another page and say this erro
{"success":false,"msg":"solusvmpro_Custom_reboot not found"}.

The bottom start stop buttons work but the top don't please fix this.

**Comment by DavidBrockway** [comment]
//

**Comment by powerpbx** [comment]
Try enable module debug logging in WHMCS.

Utilities > Logs > Module Log.

Press the reboot button and then view the log to see if there are any clues.  Action buttons including reboot work ok for us.

**Comment by jazzy348** [comment]
I'm having the same issue, I have this for the log..

Array
(
    [status] => error
    [statusmsg] => Virtual server not found
)

The virtual machine does exist, WHMCS created it perfectly fine.

**Comment by jturner** [comment]
We are seeing the same issue as @DavidBrockway. It sounds like this issue has been confirmed, or at least recognized by Solus support.

**Comment by prado1991** [comment]
will be fixed in new version
